openapi: 3.0.1
info:
    title: ServiceNow Change Request Details
    description: Get information about ServiceNow Change Requests. You can retrieve information like state, assignment group, priority, comments about particular change requests.
    version: "v1"
servers:
    - url: http://localhost:5001
paths:
    /change_request/{number}:
        get:
            operationId: getChangeRequestDetails
            summary: Retrieves change request details whose number match the query string.
            parameters:
            - in: path
              name: number
              schema:
                  type: string
              required: true
              description: The number of the change request.
            responses:
              "200":
                description: OK
